version: '3.4'
  
services:
  # ROS2 and Webots with Nvidia support
  webots_simulation:
    build:
      context: .
      dockerfile: Dockerfile.ROS2Webots
      network: host
    # command: bash -c ". /entrypoint.sh create2_description spawn_robot.launch.py"
    container_name: webots_simulation
    image: ros2_webots
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
              - gpu
    devices:
      - /dev/snd
      - /dev/dri
    environment:
      # - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - SSH_AUTH_SOCK=$SSH_AUTH_SOCK
    privileged: true
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    user: root
    volumes:
      - /home/$USER/cocobots_ws/src:/cocobots_ws/src:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./entrypoint.sh:/entrypoint.sh
      - /dev/bus/usb:/dev/bus/usb
      - $SSH_AUTH_SOCK:$SSH_AUTH_SOCK
    working_dir: /cocobots_ws
